/**
 * Canonical SELECT field list for the patients table.
 * Re-use this constant whenever you need the full patient row.
 *
 * All column aliases match the camelCase property names used by the front-end
 * (i.e. the Patient type in lib/types.ts).
 */
export const PATIENT_SELECT_FIELDS = `
  id,
  nev,
  taj,
  telefonszam,
  szuletesi_datum as "szuletesiDatum",
  nem,
  email,
  cim,
  varos,
  iranyitoszam,
  beutalo_orvos as "beutaloOrvos",
  beutalo_intezmeny as "beutaloIntezmeny",
  beutalo_indokolas as "beutaloIndokolas",
  primer_mutet_leirasa as "primerMutetLeirasa",
  mutet_ideje as "mutetIdeje",
  szovettani_diagnozis as "szovettaniDiagnozis",
  nyaki_blokkdisszekcio as "nyakiBlokkdisszekcio",
  alkoholfogyasztas,
  dohanyzas_szam as "dohanyzasSzam",
  kezelesre_erkezes_indoka as "kezelesreErkezesIndoka",
  maxilladefektus_van as "maxilladefektusVan",
  brown_fuggoleges_osztaly as "brownFuggolegesOsztaly",
  brown_vizszintes_komponens as "brownVizszintesKomponens",
  mandibuladefektus_van as "mandibuladefektusVan",
  kovacs_dobak_osztaly as "kovacsDobakOsztaly",
  nyelvmozgasok_akadalyozottak as "nyelvmozgásokAkadályozottak",
  gombocos_beszed as "gombocosBeszed",
  nyalmirigy_allapot as "nyalmirigyAllapot",
  fabian_fejerdy_protetikai_osztaly_felso as "fabianFejerdyProtetikaiOsztalyFelso",
  fabian_fejerdy_protetikai_osztaly_also as "fabianFejerdyProtetikaiOsztalyAlso",
  radioterapia,
  radioterapia_dozis as "radioterapiaDozis",
  radioterapia_datum_intervallum as "radioterapiaDatumIntervallum",
  chemoterapia,
  chemoterapia_leiras as "chemoterapiaLeiras",
  fabian_fejerdy_protetikai_osztaly as "fabianFejerdyProtetikaiOsztaly",
  kezeleoorvos,
  kezeleoorvos_intezete as "kezeleoorvosIntezete",
  felvetel_datuma as "felvetelDatuma",
  felso_fogpotlas_van as "felsoFogpotlasVan",
  felso_fogpotlas_mikor as "felsoFogpotlasMikor",
  felso_fogpotlas_keszito as "felsoFogpotlasKeszito",
  felso_fogpotlas_elegedett as "felsoFogpotlasElegedett",
  felso_fogpotlas_problema as "felsoFogpotlasProblema",
  also_fogpotlas_van as "alsoFogpotlasVan",
  also_fogpotlas_mikor as "alsoFogpotlasMikor",
  also_fogpotlas_keszito as "alsoFogpotlasKeszito",
  also_fogpotlas_elegedett as "alsoFogpotlasElegedett",
  also_fogpotlas_problema as "alsoFogpotlasProblema",
  meglevo_fogak as "meglevoFogak",
  felso_fogpotlas_tipus as "felsoFogpotlasTipus",
  also_fogpotlas_tipus as "alsoFogpotlasTipus",
  meglevo_implantatumok as "meglevoImplantatumok",
  nem_ismert_poziciokban_implantatum as "nemIsmertPoziciokbanImplantatum",
  nem_ismert_poziciokban_implantatum_reszletek as "nemIsmertPoziciokbanImplantatumRészletek",
  tnm_staging as "tnmStaging",
  bno,
  diagnozis,
  baleset_idopont as "balesetIdopont",
  baleset_etiologiaja as "balesetEtiologiaja",
  baleset_egyeb as "balesetEgyeb",
  veleszuletett_rendellenessegek as "veleszuletettRendellenessegek",
  veleszuletett_mutetek_leirasa as "veleszuletettMutetekLeirasa",
  kezelesi_terv_felso as "kezelesiTervFelso",
  kezelesi_terv_also as "kezelesiTervAlso",
  kezelesi_terv_arcot_erinto as "kezelesiTervArcotErinto",
  kortorteneti_osszefoglalo as "kortortenetiOsszefoglalo",
  kezelesi_terv_melleklet as "kezelesiTervMelleklet",
  szakorvosi_velemeny as "szakorvosiVelemény",
  halal_datum as "halalDatum",
  created_at as "createdAt",
  updated_at as "updatedAt",
  created_by as "createdBy",
  updated_by as "updatedBy"
`;
